
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* image
* filename: /Users/vitaliy/Fonts/In/Image_5V_ico.xml
* name: Image_5V_Ico
*
* preset name: My_Settings
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 128
* split to rows: no
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: yes
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
*/
#include "fonts.h"



static const uint8_t image_data_Image_5V_Ico[22] = {
    // ∙███████████████∙
    // █∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙█
    // █∙∙∙████∙∙█∙█∙∙∙█
    // █∙∙∙█∙∙∙∙∙█∙█∙∙∙█
    // █∙∙∙███∙∙∙█∙█∙∙∙█
    // █∙∙∙∙∙∙█∙∙█∙█∙∙∙█
    // █∙∙∙∙∙∙█∙∙█∙█∙∙∙█
    // █∙∙∙███∙∙∙∙█∙∙∙∙█
    // █∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙█
    // ∙███████████████∙
    0x7f, 0xff, 0x40, 0x00, 0x63, 0xca, 0x31, 0x05, 0x18, 0xe2, 0x8c, 0x09, 0x46, 0x04, 0xa3, 0x1c, 0x21, 0x80, 0x00, 0xbf, 0xff, 0xbf
};
const tImage Image_5V_Ico = { image_data_Image_5V_Ico, 17, 10,
    8 };
