
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* image
* filename: /Users/vitaliy/Fonts/In/Image_Remaning_Time.xml
* name: Image_Remaining_Time
*
* preset name: My_Settings
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 128
* split to rows: no
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: yes
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
*/
#include "fonts.h"



static const uint8_t image_data_Image_Remaining_Time[22] = {
    // ∙███████████████∙
    // █∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙█
    // █∙███∙∙██∙█∙∙∙█∙█
    // █∙█∙∙█∙█∙∙██∙██∙█
    // █∙█∙∙█∙██∙█∙█∙█∙█
    // █∙███∙∙█∙∙█∙∙∙█∙█
    // █∙█∙∙█∙█∙∙█∙∙∙█∙█
    // █∙█∙∙█∙██∙█∙∙∙█∙█
    // █∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙█
    // ∙███████████████∙
    0x7f, 0xff, 0x40, 0x00, 0x6e, 0x68, 0xb4, 0xa6, 0xda, 0x5a, 0xad, 0xc9, 0x16, 0x94, 0x8b, 0x4b, 0x45, 0x80, 0x00, 0xbf, 0xff, 0xbf
};
const tImage Image_Remaining_Time = { image_data_Image_Remaining_Time, 17, 10,
    8 };
