
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* image
* filename: /Users/vitaliy/Fonts/In/Image_Get_Status_Info.xml
* name: Image_Get_Status_Info
*
* preset name: My_Settings
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 128
* split to rows: no
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: yes
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
*/
#include "fonts.h"



static const uint8_t image_data_Image_Get_Status_Info[79] = {
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙██████████████████∙∙∙∙
    // ∙∙█∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙█∙∙∙
    // ∙∙█∙███∙█∙∙█∙███∙███∙█∙∙∙
    // ∙∙█∙∙█∙∙█∙∙█∙█∙∙∙█∙█∙██∙∙
    // ∙∙█∙∙█∙∙██∙█∙██∙∙█∙█∙██∙∙
    // ∙∙█∙∙█∙∙█∙██∙█∙∙∙█∙█∙██∙∙
    // ∙∙█∙∙█∙∙█∙∙█∙█∙∙∙█∙█∙██∙∙
    // ∙∙█∙███∙█∙∙█∙█∙∙∙███∙█∙∙∙
    // ∙∙█∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙█∙∙∙
    // ∙∙∙██████████████████∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙███∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙█∙∙∙█∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙█∙∙∙∙∙████∙∙█∙∙∙∙∙∙∙
    // ∙∙∙∙∙█∙∙∙∙∙█∙∙█∙███∙∙∙∙∙∙
    // ∙∙∙∙∙█∙███∙████∙∙█∙∙∙∙∙∙∙
    // ∙∙∙∙∙█∙∙∙█∙█∙∙∙∙∙█∙∙∙∙∙∙∙
    // ∙∙∙∙∙█∙∙∙█∙█∙∙∙∙∙█∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙███∙∙████∙∙██∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x03, 0xff, 0xff, 0x02, 0x00, 0x00, 0x41, 0x74, 0xbb, 0xa0, 0x92, 0x51, 0x58, 0x49, 0xac, 0xac, 0x24, 0xb4, 0x56, 0x12, 0x4a, 0x2b, 0x0b, 0xa5, 0x1d, 0x04, 0x00, 0x00, 0x81, 0xff, 0xff, 0x80, 0x00, 0x00, 0x00, 0x0e, 0x00, 0x00, 0x08, 0x80, 0x00, 0x04, 0x1e, 0x40, 0x02, 0x09, 0x70, 0x01, 0x77, 0x90, 0x00, 0x8a, 0x08, 0x00, 0x45, 0x04, 0x00, 0x1c, 0xf3, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x7f
};
const tImage Image_Get_Status_Info = { image_data_Image_Get_Status_Info, 25, 25,
    8 };
