
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* image
* filename: /Users/vitaliy/Fonts/In/Image_Apply.xml
* name: Image_Apply
*
* preset name: My_Settings
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 128
* split to rows: no
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: yes
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
*/
#include "fonts.h"



static const uint8_t image_data_Image_Apply[72] = {
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙██████∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙█████████∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙████∙∙∙∙██∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙███∙∙∙∙∙∙∙∙∙∙∙█∙∙∙∙
    // ∙∙∙∙███∙∙∙∙∙∙∙∙∙∙∙██∙∙∙∙
    // ∙∙∙███∙∙∙∙∙∙∙∙∙∙∙██∙∙∙∙∙
    // ∙∙∙██∙∙∙∙∙∙∙∙∙∙∙██∙∙∙∙∙∙
    // ∙∙███∙∙∙∙∙∙∙∙∙∙██∙∙∙∙∙∙∙
    // ∙∙██∙∙∙∙∙∙∙∙∙∙██∙∙∙∙█∙∙∙
    // ∙∙██∙∙∙██∙∙∙∙██∙∙∙∙∙██∙∙
    // ∙∙██∙∙∙∙██∙∙██∙∙∙∙∙∙██∙∙
    // ∙∙██∙∙∙∙∙████∙∙∙∙∙∙∙██∙∙
    // ∙∙███∙∙∙∙∙██∙∙∙∙∙∙∙███∙∙
    // ∙∙∙██∙∙∙∙∙∙∙∙∙∙∙∙∙∙██∙∙∙
    // ∙∙∙███∙∙∙∙∙∙∙∙∙∙∙∙███∙∙∙
    // ∙∙∙∙███∙∙∙∙∙∙∙∙∙∙███∙∙∙∙
    // ∙∙∙∙∙███∙∙∙∙∙∙∙∙███∙∙∙∙∙
    // ∙∙∙∙∙∙████∙∙∙∙████∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙██████████∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙██████∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x7e, 0x00, 0x01, 0xff, 0x00, 0x03, 0xc3, 0x00, 0x07, 0x00, 0x10, 0x0e, 0x00, 0x30, 0x1c, 0x00, 0x60, 0x18, 0x00, 0xc0, 0x38, 0x01, 0x80, 0x30, 0x03, 0x08, 0x31, 0x86, 0x0c, 0x30, 0xcc, 0x0c, 0x30, 0x78, 0x0c, 0x38, 0x30, 0x1c, 0x18, 0x00, 0x18, 0x1c, 0x00, 0x38, 0x0e, 0x00, 0x70, 0x07, 0x00, 0xe0, 0x03, 0xc3, 0xc0, 0x01, 0xff, 0x80, 0x00, 0x7e, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};
const tImage Image_Apply = { image_data_Image_Apply, 24, 24,
    8 };
