
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* image
* filename: /Users/vitaliy/Fonts/In/Image_Current_mAh.xml
* name: Image_Current_mAh_Ico
*
* preset name: My_Settings
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 128
* split to rows: no
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: yes
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
*/
#include "fonts.h"



static const uint8_t image_data_Image_Current_mAh_Ico[32] = {
        // ∙███████████████████████∙
        // █∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙█
        // █∙∙∙∙██∙∙∙∙∙∙∙∙█∙∙█∙█∙∙∙█
        // █∙∙∙█∙∙∙█∙∙∙█∙█∙█∙█∙█∙∙∙█
        // █∙∙∙█∙∙∙██∙██∙█∙█∙███∙∙∙█
        // █∙∙∙█∙∙∙█∙█∙█∙███∙█∙█∙∙∙█
        // █∙∙∙█∙∙∙█∙∙∙█∙█∙█∙█∙█∙∙∙█
        // █∙∙∙∙██∙█∙∙∙█∙█∙█∙█∙█∙∙∙█
        // █∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙█
        // ∙███████████████████████∙
        0x7f, 0xff, 0xff, 0x40, 0x00, 0x00, 0x61, 0x80, 0x4a, 0x31, 0x11, 0x55, 0x18, 0x8d, 0xab, 0x8c, 0x45, 0x5d, 0x46, 0x22, 0x2a, 0xa3, 0x0d, 0x15, 0x51, 0x80, 0x00, 0x00, 0xbf, 0xff, 0xff, 0xbf
};
const tImage Image_Current_mAh_Ico = { image_data_Image_Current_mAh_Ico, 25, 10,
                                       8 };