
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* image
* filename: /Users/vitaliy/Fonts/In/Image_Buzzer_On_Ico.xml
* name: Image_Buzzer_On_Ico
*
* preset name: My_Settings
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 128
* split to rows: no
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: yes
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
*/
#include "fonts.h"



static const uint8_t image_data_Image_Buzzer_On_Ico[36] = {
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙██∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙█∙█∙∙∙∙∙∙∙∙
    // ∙∙∙████∙∙█∙∙█∙∙∙∙∙
    // ∙∙∙█∙∙█∙∙█∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙█∙∙█∙█∙∙█∙∙∙
    // ∙∙∙█∙∙█∙∙█∙∙█∙█∙∙∙
    // ∙∙∙█∙∙█∙∙█∙∙█∙█∙∙∙
    // ∙∙∙█∙∙█∙∙█∙█∙∙█∙∙∙
    // ∙∙∙█∙∙█∙∙█∙∙∙█∙∙∙∙
    // ∙∙∙████∙∙█∙∙█∙∙∙∙∙
    // ∙∙∙∙∙∙∙█∙█∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙██∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x00, 0x0c, 0x00, 0x05, 0x00, 0x1e, 0x48, 0x04, 0x91, 0x01, 0x25, 0x20, 0x49, 0x28, 0x12, 0x4a, 0x04, 0x94, 0x81, 0x24, 0x40, 0x79, 0x20, 0x01, 0x40, 0x00, 0x30, 0x00, 0x00, 0x00, 0x00, 0x00
};
const tImage Image_Buzzer_On_Ico = { image_data_Image_Buzzer_On_Ico, 18, 16,
    8 };
