
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* image
* filename: /Users/vitaliy/Fonts/In/Image_Power_On_Time.xml
* name: Image_Power_On_Time
*
* preset name: My_Settings
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 128
* split to rows: no
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: yes
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
*/
#include "fonts.h"



static const uint8_t image_data_Image_Power_On_Time[22] = {
        // ∙███████████████∙
        // █∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙█
        // █∙∙███∙█∙∙∙∙∙∙∙∙█
        // █∙∙∙█∙∙∙∙∙∙∙∙∙∙∙█
        // █∙∙∙█∙∙█∙██∙██∙∙█
        // █∙∙∙█∙∙█∙█∙█∙█∙∙█
        // █∙∙∙█∙∙█∙█∙∙∙█∙∙█
        // █∙∙∙█∙∙█∙█∙∙∙█∙∙█
        // █∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙█
        // ∙███████████████∙
        0x7f, 0xff, 0x40, 0x00, 0x67, 0x40, 0x31, 0x00, 0x18, 0x96, 0xcc, 0x4a, 0xa6, 0x25, 0x13, 0x12, 0x89, 0x80, 0x00, 0xbf, 0xff, 0xbf
};
const tImage Image_Power_On_Time = { image_data_Image_Power_On_Time, 17, 10,
                                     8 };
