
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* image
* filename: /Users/vitaliy/Fonts/In/Image_Set_12V.xml
* name: Image_Set_12V
*
* preset name: My_Settings
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 128
* split to rows: no
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: yes
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
*/
#include "image.h"



static const uint8_t image_data_Image_Set_12V[36] = {
        // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
        // ∙∙████∙∙∙∙██████∙∙
        // ∙∙████∙∙∙∙██████∙∙
        // ∙∙∙∙██∙∙∙∙██∙∙██∙∙
        // ∙∙∙∙██∙∙∙∙██∙∙██∙∙
        // ∙∙∙∙██∙∙∙∙∙∙∙∙██∙∙
        // ∙∙∙∙██∙∙∙∙∙∙∙∙██∙∙
        // ∙∙∙∙██∙∙∙∙∙∙∙██∙∙∙
        // ∙∙∙∙██∙∙∙∙∙∙██∙∙∙∙
        // ∙∙∙∙██∙∙∙∙∙██∙∙∙∙∙
        // ∙∙∙∙██∙∙∙∙██∙∙∙∙∙∙
        // ∙∙∙∙██∙∙∙∙██∙∙∙∙∙∙
        // ∙∙∙∙██∙∙∙∙██∙∙∙∙∙∙
        // ∙∙██████∙∙██████∙∙
        // ∙∙██████∙∙██████∙∙
        // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
        0x00, 0x00, 0x0f, 0x0f, 0xc3, 0xc3, 0xf0, 0x30, 0xcc, 0x0c, 0x33, 0x03, 0x00, 0xc0, 0xc0, 0x30, 0x30, 0x18, 0x0c, 0x0c, 0x03, 0x06, 0x00, 0xc3, 0x00, 0x30, 0xc0, 0x0c, 0x30, 0x0f, 0xcf, 0xc3, 0xf3, 0xf0, 0x00, 0x00
};
const tImage Image_Set_12V = { image_data_Image_Set_12V, 18, 16,
                               8 };
