
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* image
* filename: unsaved
* name: Image_Used_mAh
*
* preset name: My_Settings
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 128
* split to rows: no
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: yes
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
*/
#include "image.h"



static const uint8_t image_data_Image_Used_mAh[22] = {
        // ∙███████████████∙
        // █∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙█
        // █∙∙∙∙∙∙∙∙█∙∙█∙█∙█
        // █∙∙∙∙∙∙∙█∙█∙█∙█∙█
        // █∙██∙██∙█∙█∙███∙█
        // █∙█∙█∙█∙███∙█∙█∙█
        // █∙█∙∙∙█∙█∙█∙█∙█∙█
        // █∙█∙∙∙█∙█∙█∙█∙█∙█
        // █∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙█
        // ∙███████████████∙
        0x7f, 0xff, 0x40, 0x00, 0x60, 0x12, 0xb0, 0x15, 0x5b, 0x6a, 0xed, 0x57, 0x56, 0x8a, 0xab, 0x45, 0x55, 0x80, 0x00, 0xbf, 0xff, 0xbf
};
const tImage Image_Used_mAh = { image_data_Image_Used_mAh, 17, 10,
                                8 };