
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* image
* filename: unsaved
* name: Image_Exit
*
* preset name: Monochrome
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 128
* split to rows: no
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: yes
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
*/
#include "fonts.h"



static const uint8_t image_data_Image_Exit[79] = {
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙███████████████∙∙
    // ∙∙∙∙∙∙∙█████████████████∙
    // ∙∙∙∙∙∙∙██∙∙∙∙∙∙∙∙∙∙∙∙∙██∙
    // ∙∙∙∙∙∙∙██∙∙∙∙∙∙∙∙∙∙∙∙∙██∙
    // ∙∙∙∙∙∙∙██∙∙∙∙∙∙∙∙∙∙∙∙∙██∙
    // ∙∙∙∙∙∙∙██∙∙∙∙∙∙∙∙∙∙∙∙∙██∙
    // ∙∙∙∙∙∙∙██∙∙∙∙∙∙∙∙∙∙∙∙∙██∙
    // ∙∙∙∙∙∙∙██∙∙∙∙███∙∙∙∙∙∙██∙
    // ∙∙∙∙∙∙∙██∙∙∙∙█∙██∙∙∙∙∙██∙
    // ∙∙∙∙∙∙∙██∙∙∙∙█∙∙██∙∙∙∙██∙
    // ∙█████████████∙∙∙██∙∙∙██∙
    // ∙█∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙██∙∙██∙
    // ∙█████████████∙∙∙██∙∙∙██∙
    // ∙∙∙∙∙∙∙██∙∙∙∙█∙∙██∙∙∙∙██∙
    // ∙∙∙∙∙∙∙██∙∙∙∙█∙██∙∙∙∙∙██∙
    // ∙∙∙∙∙∙∙██∙∙∙∙███∙∙∙∙∙∙██∙
    // ∙∙∙∙∙∙∙██∙∙∙∙∙∙∙∙∙∙∙∙∙██∙
    // ∙∙∙∙∙∙∙██∙∙∙∙∙∙∙∙∙∙∙∙∙██∙
    // ∙∙∙∙∙∙∙██∙∙█∙█∙█∙█∙█∙∙██∙
    // ∙∙∙∙∙∙∙██∙∙█∙█∙█∙█∙█∙∙██∙
    // ∙∙∙∙∙∙∙██∙∙∙∙∙∙∙∙∙∙∙∙∙██∙
    // ∙∙∙∙∙∙∙█████████████████∙
    // ∙∙∙∙∙∙∙∙███████████████∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x7f, 0xff, 0x00, 0x7f, 0xff, 0xc0, 0x30, 0x00, 0x60, 0x18, 0x00, 0x30, 0x0c, 0x00, 0x18, 0x06, 0x00, 0x0c, 0x03, 0x00, 0x06, 0x01, 0x87, 0x03, 0x00, 0xc2, 0xc1, 0x80, 0x61, 0x30, 0xcf, 0xff, 0x8c, 0x64, 0x00, 0x03, 0x33, 0xff, 0xe3, 0x18, 0x06, 0x13, 0x0c, 0x03, 0x0b, 0x06, 0x01, 0x87, 0x03, 0x00, 0xc0, 0x01, 0x80, 0x60, 0x00, 0xc0, 0x32, 0xaa, 0x60, 0x19, 0x55, 0x30, 0x0c, 0x00, 0x18, 0x07, 0xff, 0xfc, 0x01, 0xff, 0xfc, 0x00, 0x00, 0x00, 0x00
};
const tImage Image_Exit = { image_data_Image_Exit, 25, 25,
    8 };

