
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* image
* filename: /Users/vitaliy/Fonts/In/Image_Set_Timer_Off.xml
* name: Image_Set_Timer_Off
*
* preset name: My_Settings
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 128
* split to rows: no
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: yes
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
*/
#include "fonts.h"



static const uint8_t image_data_Image_Set_Timer_Off[79] = {
        // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
        // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
        // ∙∙∙∙∙∙∙∙∙∙██∙∙∙∙∙∙∙∙∙∙∙∙∙
        // ∙∙∙∙∙∙∙∙∙∙██∙█∙∙∙∙∙∙∙∙∙∙∙
        // ∙∙∙∙∙∙∙█∙∙∙∙∙∙█∙∙∙∙∙∙∙∙∙∙
        // ∙∙∙∙∙∙∙∙█∙∙∙∙∙∙█∙∙∙∙∙∙∙∙∙
        // ∙∙∙∙∙∙█∙∙█∙∙∙∙∙∙█∙∙∙∙∙∙∙∙
        // ∙∙∙∙∙∙█∙∙∙█∙∙∙∙∙█∙∙∙∙∙∙∙∙
        // ∙∙∙∙∙∙█∙∙∙∙█∙∙∙∙█∙∙∙∙∙∙∙∙
        // ∙∙∙∙∙∙█∙∙∙∙∙∙∙∙∙█∙∙∙∙∙∙∙∙
        // ∙∙∙∙∙∙∙█∙∙∙∙∙∙∙█∙∙█∙∙∙∙∙∙
        // ∙∙∙∙∙∙∙∙█∙∙∙∙∙█∙∙∙█∙∙∙∙∙∙
        // ∙∙∙∙∙∙∙∙∙█∙∙∙█∙∙∙███∙∙∙∙∙
        // ∙∙∙∙∙∙∙∙∙∙███∙∙∙∙∙█∙∙∙∙∙∙
        // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙█∙∙∙∙∙∙
        // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙██∙∙∙∙∙
        // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
        // ∙∙∙∙∙███∙∙███∙███∙∙∙∙∙∙∙∙
        // ∙∙∙∙∙█∙█∙∙█∙∙∙█∙∙∙∙∙∙∙∙∙∙
        // ∙∙∙∙∙█∙█∙∙██∙∙██∙∙∙∙∙∙∙∙∙
        // ∙∙∙∙∙█∙█∙∙█∙∙∙█∙∙∙∙∙∙∙∙∙∙
        // ∙∙∙∙∙█∙█∙∙█∙∙∙█∙∙∙∙∙∙∙∙∙∙
        // ∙∙∙∙∙███∙∙█∙∙∙█∙∙∙∙∙∙∙∙∙∙
        // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
        // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0c, 0x00, 0x00, 0x06, 0x80, 0x00, 0x10, 0x20, 0x00, 0x04, 0x08, 0x00, 0x09, 0x02, 0x00, 0x04, 0x41, 0x00, 0x02, 0x10, 0x80, 0x01, 0x00, 0x40, 0x00, 0x40, 0x48, 0x00, 0x10, 0x44, 0x00, 0x04, 0x47, 0x00, 0x01, 0xc1, 0x00, 0x00, 0x00, 0x80, 0x00, 0x00, 0x60, 0x00, 0x00, 0x00, 0x03, 0x9d, 0xc0, 0x01, 0x48, 0x80, 0x00, 0xa6, 0x60, 0x00, 0x52, 0x20, 0x00, 0x29, 0x10, 0x00, 0x1c, 0x88, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x7f
};
const tImage Image_Set_Timer_Off = { image_data_Image_Set_Timer_Off, 25, 25,
    8 };
