
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* image
* filename: /Users/vitaliy/Fonts/In/Image_USB_ico.xml
* name: Image_USB_Ico
*
* preset name: My_Settings
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 128
* split to rows: no
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: yes
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
*/
#include "fonts.h"



static const uint8_t image_data_Image_USB_Ico[22] = {
    // ∙███████████████∙
    // █∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙█
    // █∙█∙∙█∙███∙███∙∙█
    // █∙█∙∙█∙█∙∙∙█∙∙█∙█
    // █∙█∙∙█∙███∙████∙█
    // █∙█∙∙█∙∙∙█∙█∙∙█∙█
    // █∙█∙∙█∙∙∙█∙█∙∙█∙█
    // █∙∙██∙∙███∙███∙∙█
    // █∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙█
    // ∙███████████████∙
    0x7f, 0xff, 0x40, 0x00, 0x69, 0x77, 0x34, 0xa2, 0x5a, 0x5d, 0xed, 0x22, 0x96, 0x91, 0x4b, 0x33, 0xb9, 0x80, 0x00, 0xbf, 0xff, 0xbf
};
const tImage Image_USB_Ico = { image_data_Image_USB_Ico, 17, 10,
    8 };
