
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* image
* filename: C:/Users/User/Image_A.xml
* name: Image_B
*
* preset name: Monochrome
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 128
* split to rows: no
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: yes
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
*/
#include "image.h"


static const uint8_t image_data_Image_B[21] = {
  // ∙∙∙∙∙∙∙∙∙∙∙
  // ∙∙███████∙∙
  // ∙█∙∙∙∙∙∙∙█∙
  // ∙█∙████∙∙█∙
  // ∙█∙█∙∙∙█∙█∙
  // ∙█∙█∙∙∙█∙█∙
  // ∙█∙█∙∙∙█∙█∙
  // ∙█∙████∙∙█∙
  // ∙█∙█∙∙∙█∙█∙
  // ∙█∙█∙∙∙█∙█∙
  // ∙█∙█∙∙∙█∙█∙
  // ∙█∙████∙∙█∙
  // ∙█∙∙∙∙∙∙∙█∙
  // ∙∙███████∙∙
  // ∙∙∙∙∙∙∙∙∙∙∙
  0x00, 0x07, 0xf1, 0x01, 0x2f, 0x25, 0x14, 0xa2, 0x94, 0x52, 0xf2, 0x51, 0x4a, 0x29, 0x45, 0x2f, 0x24, 0x04, 0x7f, 0x00, 0x00
};
const tImage Image_B = { image_data_Image_B, 11, 15, 8 };



static const uint8_t image_data_Image_A[21] = {
  // ∙∙∙∙∙∙∙∙∙∙∙
  // ∙∙███████∙∙
  // ∙█∙∙∙∙∙∙∙█∙
  // ∙█∙∙███∙∙█∙
  // ∙█∙█∙∙∙█∙█∙
  // ∙█∙█∙∙∙█∙█∙
  // ∙█∙█∙∙∙█∙█∙
  // ∙█∙█████∙█∙
  // ∙█∙█∙∙∙█∙█∙
  // ∙█∙█∙∙∙█∙█∙
  // ∙█∙█∙∙∙█∙█∙
  // ∙█∙█∙∙∙█∙█∙
  // ∙█∙∙∙∙∙∙∙█∙
  // ∙∙███████∙∙
  // ∙∙∙∙∙∙∙∙∙∙∙
  0x00, 0x07, 0xf1, 0x01, 0x27, 0x25, 0x14, 0xa2, 0x94, 0x52, 0xfa, 0x51, 0x4a, 0x29, 0x45, 0x28, 0xa4, 0x04, 0x7f, 0x00, 0x00
};
const tImage Image_A = { image_data_Image_A, 11, 15, 8 };