
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* image
* filename: unsaved
* name: Image_Calibrate
*
* preset name: Monochrome
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 128
* split to rows: no
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: yes
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
*/
#include "fonts.h"



static const uint8_t image_data_Image_Calibrate[79] = {
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙███████████████████████∙
    // █████████████████████████
    // █∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙█
    // █∙█∙███████████████████∙█
    // █∙∙∙█∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙█∙█
    // █∙█∙█∙∙∙∙∙∙∙∙∙∙███∙∙∙∙█∙█
    // █∙∙∙█∙∙█████████∙███∙∙█∙█
    // █∙█∙█∙∙█████████∙███∙∙█∙█
    // █∙∙∙█∙∙∙∙∙∙∙∙∙∙███∙∙∙∙█∙█
    // █∙█∙█∙∙∙∙∙███∙∙∙∙∙∙∙∙∙█∙█
    // █∙∙∙█∙∙████∙████████∙∙█∙█
    // █∙█∙█∙∙████∙████████∙∙█∙█
    // █∙∙∙█∙∙∙∙∙███∙∙∙∙∙∙∙∙∙█∙█
    // █∙█∙█∙∙∙∙∙∙∙∙∙███∙∙∙∙∙█∙█
    // █∙∙∙█∙∙████████∙████∙∙█∙█
    // █∙█∙█∙∙████████∙████∙∙█∙█
    // █∙∙∙█∙∙∙∙∙∙∙∙∙███∙∙∙∙∙█∙█
    // █∙█∙█∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙█∙█
    // █∙█∙███████████████████∙█
    // █∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙█
    // █████████████████████████
    // ∙███████████████████████∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x3f, 0xff, 0xff, 0xbf, 0xff, 0xff, 0xf0, 0x00, 0x00, 0x1a, 0xff, 0xff, 0xec, 0x40, 0x00, 0x16, 0xa0, 0x07, 0x0b, 0x13, 0xfe, 0xe5, 0xa9, 0xff, 0x72, 0xc4, 0x00, 0xe1, 0x6a, 0x0e, 0x00, 0xb1, 0x3d, 0xfe, 0x5a, 0x9e, 0xff, 0x2c, 0x41, 0xc0, 0x16, 0xa0, 0x0e, 0x0b, 0x13, 0xfd, 0xe5, 0xa9, 0xfe, 0xf2, 0xc4, 0x01, 0xc1, 0x6a, 0x00, 0x00, 0xb5, 0xff, 0xff, 0xd8, 0x00, 0x00, 0x0f, 0xff, 0xff, 0xfd, 0xff, 0xff, 0xfc, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};
const tImage Image_Calibrate = { image_data_Image_Calibrate, 25, 25,
    8 };

