
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* image
* filename: /Users/vitaliy/Fonts/In/Image_Buzzer.xml
* name: Image_Buzzer
*
* preset name: My_Settings
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 128
* split to rows: no
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: yes
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
*/
#include "fonts.h"



static const uint8_t image_data_Image_Buzzer[79] = {
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙██∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙█∙█∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙█∙∙█∙∙∙█∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙████∙∙∙█∙∙∙∙█∙∙∙∙∙∙
    // ∙∙∙∙∙∙█∙∙█∙∙∙█∙∙∙∙∙█∙∙∙∙∙
    // ∙∙∙∙∙∙█∙∙█∙∙∙█∙∙█∙∙█∙∙∙∙∙
    // ∙∙∙∙∙∙█∙∙█∙∙∙█∙∙∙█∙█∙∙∙∙∙
    // ∙∙∙∙∙∙█∙∙█∙∙∙█∙∙∙█∙█∙∙∙∙∙
    // ∙∙∙∙∙∙█∙∙█∙∙∙█∙∙∙█∙█∙∙∙∙∙
    // ∙∙∙∙∙∙█∙∙█∙∙∙█∙∙∙█∙█∙∙∙∙∙
    // ∙∙∙∙∙∙█∙∙█∙∙∙█∙∙█∙∙█∙∙∙∙∙
    // ∙∙∙∙∙∙█∙∙█∙∙∙█∙∙∙∙∙█∙∙∙∙∙
    // ∙∙∙∙∙∙████∙∙∙█∙∙∙∙█∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙█∙∙█∙∙∙█∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙█∙█∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙██∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙███∙█∙∙█∙∙███∙███∙███∙∙
    // ∙∙█∙█∙█∙∙█∙∙█∙█∙█∙∙∙█∙∙∙∙
    // ∙∙█∙█∙██∙█∙∙█∙█∙██∙∙██∙∙∙
    // ∙∙█∙█∙█∙██∙∙█∙█∙█∙∙∙█∙∙∙∙
    // ∙∙█∙█∙█∙∙█∙∙█∙█∙█∙∙∙█∙∙∙∙
    // ∙∙███∙█∙∙█∙∙███∙█∙∙∙█∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x06, 0x00, 0x00, 0x05, 0x00, 0x00, 0x04, 0x88, 0x00, 0x3c, 0x42, 0x00, 0x12, 0x20, 0x80, 0x09, 0x12, 0x40, 0x04, 0x88, 0xa0, 0x02, 0x44, 0x50, 0x01, 0x22, 0x28, 0x00, 0x91, 0x14, 0x00, 0x48, 0x92, 0x00, 0x24, 0x41, 0x00, 0x1e, 0x21, 0x00, 0x00, 0x91, 0x00, 0x00, 0x28, 0x00, 0x00, 0x0c, 0x00, 0x00, 0x00, 0x00, 0x0e, 0x93, 0xbb, 0x85, 0x49, 0x51, 0x02, 0xb4, 0xac, 0xc1, 0x56, 0x54, 0x40, 0xa9, 0x2a, 0x20, 0x74, 0x9d, 0x10, 0x00, 0x00, 0x00, 0x7f
};
const tImage Image_Buzzer = { image_data_Image_Buzzer, 25, 25,
    8 };
