
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* image
* filename: /Users/vitaliy/Fonts/In/Image_Set_Capasity_Design.xml
* name: Image_Set_Capasity_Design
*
* preset name: My_Settings
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 128
* split to rows: no
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: yes
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
*/
#include "fonts.h"



static const uint8_t image_data_Image_Set_Capasity_Design[79] = {
        // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
        // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
        // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
        // ∙∙∙██████████████████∙∙∙∙
        // ∙∙█∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙█∙∙∙
        // ∙∙█∙∙∙∙∙∙∙∙███∙█∙∙∙∙∙█∙∙∙
        // ∙∙█∙∙∙∙∙∙∙∙█∙█∙█∙∙∙∙∙██∙∙
        // ∙∙█∙∙██∙██∙█∙█∙██∙∙∙∙██∙∙
        // ∙∙█∙∙█∙█∙█∙███∙█∙█∙∙∙██∙∙
        // ∙∙█∙∙█∙∙∙█∙█∙█∙█∙█∙∙∙██∙∙
        // ∙∙█∙∙█∙∙∙█∙█∙█∙█∙█∙∙∙█∙∙∙
        // ∙∙█∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙█∙∙∙
        // ∙∙∙██████████████████∙∙∙∙
        // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
        // ∙∙∙∙∙█████∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
        // ∙∙∙∙∙█∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
        // ∙∙∙∙∙█∙∙∙∙∙████∙∙█∙∙∙∙∙∙∙
        // ∙∙∙∙∙█████∙█∙∙█∙███∙∙∙∙∙∙
        // ∙∙∙∙∙∙∙∙∙█∙████∙∙█∙∙∙∙∙∙∙
        // ∙∙∙∙∙∙∙∙∙█∙█∙∙∙∙∙█∙∙∙∙∙∙∙
        // ∙∙∙∙∙∙∙∙∙█∙█∙∙∙∙∙█∙∙∙∙∙∙∙
        // ∙∙∙∙∙█████∙████∙∙██∙∙∙∙∙∙
        // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
        // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
        // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x03, 0xff, 0xff, 0x02, 0x00, 0x00, 0x41, 0x00, 0xe8, 0x20, 0x80, 0x54, 0x18, 0x4d, 0xab, 0x0c, 0x25, 0x5d, 0x46, 0x12, 0x2a, 0xa3, 0x09, 0x15, 0x51, 0x04, 0x00, 0x00, 0x81, 0xff, 0xff, 0x80, 0x00, 0x00, 0x00, 0x1f, 0x00, 0x00, 0x08, 0x00, 0x00, 0x04, 0x1e, 0x40, 0x03, 0xe9, 0x70, 0x00, 0x17, 0x90, 0x00, 0x0a, 0x08, 0x00, 0x05, 0x04, 0x00, 0x3e, 0xf3, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x7f
};
const tImage Image_Set_Capasity_Design = { image_data_Image_Set_Capasity_Design, 25, 25,
    8 };
