
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* image
* filename: C:/Users/User/Image_Active_Ch.xml
* name: Image_Active_Ch
*
* preset name: Monochrome
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 128
* split to rows: no
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: yes
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
*/
#include "image.h"



static const uint8_t image_data_Image_inActive_A_Ch[11] = {
  // ∙∙█████∙∙
  // ∙█∙∙∙∙∙█∙
  // █∙∙███∙∙█
  // █∙█∙∙∙█∙█
  // █∙█████∙█
  // █∙█∙∙∙█∙█
  // █∙█∙∙∙█∙█
  // ∙█∙∙∙∙∙█∙
  // ∙∙█████∙∙
  0x3e, 0x20, 0xa7, 0x34, 0x5b, 0xed, 0x16, 0x8a, 0x82, 0x3e, 0x00
};
const tImage Image_inActive_A_Ch = { image_data_Image_inActive_A_Ch, 9, 9, 8 };


static const uint8_t image_data_Image_Active_A_Ch[11] = {
  // ∙∙█████∙∙
  // ∙███████∙
  // ███∙∙∙███
  // ██∙███∙██
  // ██∙∙∙∙∙██
  // ██∙███∙██
  // ██∙███∙██
  // ∙███████∙
  // ∙∙█████∙∙
  0x3e, 0x3f, 0xb8, 0xfb, 0xbc, 0x1e, 0xef, 0x76, 0xfe, 0x3e, 0x00
};
const tImage Image_Active_A_Ch = { image_data_Image_Active_A_Ch, 9, 9, 8 };


static const uint8_t image_data_Image_inActive_B_Ch[11] = {
  // ∙∙█████∙∙
  // ∙█∙∙∙∙∙█∙
  // █∙████∙∙█
  // █∙█∙∙∙█∙█
  // █∙█████∙█
  // █∙█∙∙∙█∙█
  // █∙████∙∙█
  // ∙█∙∙∙∙∙█∙
  // ∙∙█████∙∙
  0x3e, 0x20, 0xaf, 0x34, 0x5b, 0xed, 0x16, 0xf2, 0x82, 0x3e, 0x00
};
const tImage Image_inActive_B_Ch = { image_data_Image_inActive_B_Ch, 9, 9, 8 };


static const uint8_t image_data_Image_Active_B_Ch[11] = {
  // ∙∙█████∙∙
  // ∙███████∙
  // ██∙∙∙∙███
  // ██∙███∙██
  // ██∙∙∙∙∙██
  // ██∙███∙██
  // ██∙∙∙∙███
  // ∙███████∙
  // ∙∙█████∙∙
  0x3e, 0x3f, 0xb0, 0xfb, 0xbc, 0x1e, 0xef, 0x0e, 0xfe, 0x3e, 0x00
};
const tImage Image_Active_B_Ch = { image_data_Image_Active_B_Ch, 9, 9, 8 };

