
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* image
* filename: /Users/vitaliy/Fonts/In/Image_Exit_Menu.xml
* name: Image_Exit_Menu
*
* preset name: My_Settings
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 128
* split to rows: no
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: yes
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
*/
#include "fonts.h"



static const uint8_t image_data_Image_Exit_Menu[79] = {
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙██████∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙█∙∙∙∙∙∙█∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙█∙∙∙∙∙∙█∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙█∙∙∙∙∙∙█∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙█∙∙∙∙∙∙█∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙█∙∙∙██∙█∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙█∙∙█∙∙∙█∙∙█∙∙∙∙∙
    // ∙∙∙∙███████∙█∙∙∙█∙∙█∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙█∙∙█∙∙∙██∙█∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙█∙∙∙∙∙∙█∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙██████∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙█████∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙█∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙█∙∙∙∙∙█∙∙∙█∙█∙∙█∙∙∙∙∙
    // ∙∙∙∙█████∙∙█∙█∙∙∙∙███∙∙∙∙
    // ∙∙∙∙█∙∙∙∙∙∙∙█∙∙∙█∙∙█∙∙∙∙∙
    // ∙∙∙∙█∙∙∙∙∙∙∙█∙∙∙█∙∙█∙∙∙∙∙
    // ∙∙∙∙█∙∙∙∙∙∙█∙█∙∙█∙∙█∙∙∙∙∙
    // ∙∙∙∙█████∙█∙∙∙█∙█∙∙██∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0xf8, 0x00, 0x01, 0x02, 0x00, 0x00, 0x81, 0x00, 0x00, 0x40, 0x80, 0x00, 0x20, 0x40, 0x00, 0x11, 0xa0, 0x00, 0x48, 0x90, 0x07, 0xf4, 0x48, 0x00, 0x12, 0x34, 0x00, 0x01, 0x02, 0x00, 0x00, 0x7e, 0x00, 0x00, 0x00, 0x00, 0x3e, 0x00, 0x00, 0x10, 0x00, 0x00, 0x08, 0x22, 0x90, 0x07, 0xca, 0x1c, 0x02, 0x02, 0x24, 0x01, 0x01, 0x12, 0x00, 0x81, 0x49, 0x00, 0x7d, 0x14, 0xc0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x7f
};
const tImage Image_Exit_Menu = { image_data_Image_Exit_Menu, 25, 25,
    8 };
