
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* image
* filename: /Users/vitaliy/Fonts/In/Image_Temperature_Ico.xml
* name: Image_Temperature_Ico
*
* preset name: My_Settings
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 128
* split to rows: no
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: yes
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
*/
#include "fonts.h"



static const uint8_t image_data_Image_Temperature_Ico[22] = {
    // ∙███████████████∙
    // █∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙█
    // █∙∙∙∙∙∙█∙∙████∙∙█
    // █∙∙█∙∙█∙█∙█∙∙∙∙∙█
    // █∙███∙∙█∙∙█∙∙∙∙∙█
    // █∙∙█∙∙∙∙∙∙█∙∙∙∙∙█
    // █∙∙█∙∙∙∙∙∙█∙∙∙∙∙█
    // █∙∙███∙∙∙∙████∙∙█
    // █∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙█
    // ∙███████████████∙
    0x7f, 0xff, 0x40, 0x00, 0x60, 0x4f, 0x32, 0x54, 0x1b, 0x92, 0x0c, 0x81, 0x06, 0x40, 0x83, 0x38, 0x79, 0x80, 0x00, 0xbf, 0xff, 0xbf
};
const tImage Image_Temperature_Ico = { image_data_Image_Temperature_Ico, 17, 10,
    8 };
