
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* image
* filename: /Users/vitaliy/Fonts/In/Image_Set_I_Max.xml
* name: Image_Set_I_Max
*
* preset name: My_Settings
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 128
* split to rows: no
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: yes
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
*/
#include "fonts.h"



static const uint8_t image_data_Image_Set_I_Max[79] = {
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙██████████∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙█∙∙∙∙∙∙∙∙∙∙█∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙█∙∙∙∙██∙∙∙∙█∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙█∙∙∙████∙∙∙█∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙█∙∙∙█∙∙█∙∙∙█∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙█∙∙∙█∙∙█∙∙∙█∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙█∙∙██∙∙██∙∙█∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙█∙∙█∙∙∙∙█∙∙█∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙█∙██∙∙∙∙██∙█∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙█∙████████∙█∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙█∙█∙∙∙∙∙∙█∙█∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙█∙█∙∙∙∙∙∙█∙█∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙█∙∙∙∙∙∙∙∙∙∙█∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙██████████∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙█∙∙∙█∙∙∙█∙∙∙█∙∙∙█∙∙∙∙
    // ∙∙∙∙██∙██∙∙█∙█∙∙█∙∙∙█∙∙∙∙
    // ∙∙∙∙█∙█∙█∙█∙∙∙█∙∙█∙█∙∙∙∙∙
    // ∙∙∙∙█∙∙∙█∙█∙∙∙█∙∙∙█∙∙∙∙∙∙
    // ∙∙∙∙█∙∙∙█∙█████∙∙█∙█∙∙∙∙∙
    // ∙∙∙∙█∙∙∙█∙█∙∙∙█∙█∙∙∙█∙∙∙∙
    // ∙∙∙∙█∙∙∙█∙█∙∙∙█∙█∙∙∙█∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x7f, 0xe0, 0x00, 0x40, 0x08, 0x00, 0x21, 0x84, 0x00, 0x11, 0xe2, 0x00, 0x08, 0x91, 0x00, 0x04, 0x48, 0x80, 0x02, 0x66, 0x40, 0x01, 0x21, 0x20, 0x00, 0xb0, 0xd0, 0x00, 0x5f, 0xe8, 0x00, 0x28, 0x14, 0x00, 0x14, 0x0a, 0x00, 0x08, 0x01, 0x00, 0x03, 0xff, 0x00, 0x00, 0x00, 0x00, 0x08, 0x88, 0x88, 0x06, 0xca, 0x44, 0x02, 0xa8, 0x94, 0x01, 0x14, 0x44, 0x00, 0x8b, 0xe5, 0x00, 0x45, 0x14, 0x40, 0x22, 0x8a, 0x20, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x7f
};
const tImage Image_Set_I_Max = { image_data_Image_Set_I_Max, 25, 25,
    8 };
