
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* image
* filename: /Users/vitaliy/Fonts/In/Image_Current_I.xml
* name: Image_Current_I
*
* preset name: My_Settings
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 128
* split to rows: no
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: yes
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
*/
#include "fonts.h"


static const uint8_t image_data_Image_Current_I[22] = {
        // ∙███████████████∙
        // █∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙█
        // █∙∙███∙█∙█∙██∙∙∙█
        // █∙∙█∙∙∙█∙█∙█∙█∙∙█
        // █∙∙█∙∙∙█∙█∙█∙█∙∙█
        // █∙∙█∙∙∙█∙█∙██∙∙∙█
        // █∙∙█∙∙∙█∙█∙█∙█∙∙█
        // █∙∙███∙███∙█∙█∙∙█
        // █∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙█
        // ∙███████████████∙
        0x7f, 0xff, 0x40, 0x00, 0x67, 0x56, 0x32, 0x2a, 0x99, 0x15, 0x4c, 0x8a, 0xc6, 0x45, 0x53, 0x3b, 0xa9, 0x80, 0x00, 0xbf, 0xff, 0xbf
};
const tImage Image_Current_I = { image_data_Image_Current_I, 17, 10,
                                 8 };