
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* image
* filename: unsaved
* name: Image_Settings
*
* preset name: Monochrome
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 128
* split to rows: no
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: yes
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
*/
#include "fonts.h"



static const uint8_t image_data_Image_Settings[79] = {
    // ∙∙∙∙∙∙∙∙∙∙∙███∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙██∙██∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙█∙∙∙█∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙███∙∙██∙∙∙██∙∙███∙∙∙∙
    // ∙∙∙██∙████∙∙∙∙∙████∙██∙∙∙
    // ∙∙∙█∙∙∙∙∙∙█████∙∙∙∙∙∙█∙∙∙
    // ∙∙∙██∙∙∙∙█∙∙∙∙∙█∙∙∙∙██∙∙∙
    // ∙∙∙∙█∙∙∙█∙∙███∙∙█∙∙∙█∙∙∙∙
    // ∙∙∙∙█∙∙█∙∙██∙██∙∙█∙∙█∙∙∙∙
    // ∙∙∙██∙█∙∙█∙∙█∙∙█∙∙█∙██∙∙∙
    // ∙███∙∙█∙█∙∙∙█∙∙∙█∙█∙∙███∙
    // ██∙∙∙█∙∙█∙∙∙█∙∙∙█∙∙█∙∙∙██
    // █∙∙∙∙█∙█∙███████∙█∙█∙∙∙∙█
    // ██∙∙∙█∙∙█∙∙∙█∙∙∙█∙∙█∙∙∙██
    // ∙███∙∙█∙█∙∙∙█∙∙∙█∙█∙∙███∙
    // ∙∙∙██∙█∙∙█∙∙█∙∙█∙∙█∙██∙∙∙
    // ∙∙∙∙█∙∙█∙∙██∙██∙∙█∙∙█∙∙∙∙
    // ∙∙∙∙█∙∙∙█∙∙███∙∙█∙∙∙█∙∙∙∙
    // ∙∙∙██∙∙∙∙█∙∙∙∙∙█∙∙∙∙██∙∙∙
    // ∙∙∙█∙∙∙∙∙∙█████∙∙∙∙∙∙█∙∙∙
    // ∙∙∙██∙████∙∙∙∙∙████∙██∙∙∙
    // ∙∙∙∙███∙∙██∙∙∙██∙∙███∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙█∙∙∙█∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙██∙██∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙███∙∙∙∙∙∙∙∙∙∙∙
    0x00, 0x1c, 0x00, 0x00, 0x1b, 0x00, 0x00, 0x08, 0x80, 0x01, 0xcc, 0x67, 0x01, 0xbc, 0x1e, 0xc0, 0x81, 0xf0, 0x20, 0x61, 0x04, 0x30, 0x11, 0x39, 0x10, 0x09, 0x36, 0x48, 0x0d, 0x24, 0x96, 0x1c, 0xa2, 0x29, 0xd8, 0x91, 0x12, 0x38, 0x57, 0xf5, 0x0e, 0x24, 0x44, 0x8d, 0xca, 0x22, 0x9c, 0x34, 0x92, 0x58, 0x09, 0x36, 0x48, 0x04, 0x4e, 0x44, 0x06, 0x10, 0x43, 0x02, 0x07, 0xc0, 0x81, 0xbc, 0x1e, 0xc0, 0x73, 0x19, 0xc0, 0x00, 0x88, 0x00, 0x00, 0x6c, 0x00, 0x00, 0x1c, 0x00, 0x00
};
const tImage Image_Settings = { image_data_Image_Settings, 25, 25,
    8 };

