
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* font
* filename: unsaved
* name: Font_Let_9x13
* family: Mongolian Baiti
* size: 14
* style: Regular
* included characters: 0123456789
* antialiasing: no
* type: proportional
* encoding: UTF-8
* unicode bom: no
*
* preset name: Monochrome
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 128
* split to rows: no
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: yes
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
 typedef struct {
     long int code;
     const tImage *image;
     } tChar;
 typedef struct {
     int length;
     const tChar *chars;
     } tFont;
*/

#include "fonts.h"



#if (0x0 == 0x0)
static const uint8_t image_data_Font_Let_9x13_0x30[15] = {
  // ∙███████∙
  // █∙∙∙∙∙∙∙█
  // █∙∙███∙∙█
  // █∙█∙∙∙█∙█
  // █∙█∙∙∙█∙█
  // █∙█∙∙∙█∙█
  // █∙█∙∙∙█∙█
  // █∙█∙∙∙█∙█
  // █∙█∙∙∙█∙█
  // █∙█∙∙∙█∙█
  // █∙∙███∙∙█
  // █∙∙∙∙∙∙∙█
  // ∙███████∙
  0x7f, 0x40, 0x67, 0x34, 0x5a, 0x2d, 0x16, 0x8b, 0x45, 0xa2, 0xd1, 0x67, 0x30, 0x17, 0xf0
};
static const tImage Font_Let_9x13_0x30 = { image_data_Font_Let_9x13_0x30,
                                           9, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_Let_9x13_0x31[15] = {
  // ∙███████∙
  // █∙∙∙∙∙∙∙█
  // █∙∙██∙∙∙█
  // █∙∙∙█∙∙∙█
  // █∙∙∙█∙∙∙█
  // █∙∙∙█∙∙∙█
  // █∙∙∙█∙∙∙█
  // █∙∙∙█∙∙∙█
  // █∙∙∙█∙∙∙█
  // █∙∙∙█∙∙∙█
  // █∙∙███∙∙█
  // █∙∙∙∙∙∙∙█
  // ∙███████∙
  0x7f, 0x40, 0x66, 0x31, 0x18, 0x8c, 0x46, 0x23, 0x11, 0x88, 0xc4, 0x67, 0x30, 0x17, 0xf0
};
static const tImage Font_Let_9x13_0x31 = { image_data_Font_Let_9x13_0x31,
                                           9, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_Let_9x13_0x32[15] = {
  // ∙███████∙
  // █∙∙∙∙∙∙∙█
  // █∙█████∙█
  // █∙∙∙∙∙█∙█
  // █∙∙∙∙∙█∙█
  // █∙∙∙∙∙█∙█
  // █∙∙∙∙█∙∙█
  // █∙∙∙█∙∙∙█
  // █∙∙█∙∙∙∙█
  // █∙█∙∙∙∙∙█
  // █∙█████∙█
  // █∙∙∙∙∙∙∙█
  // ∙███████∙
  0x7f, 0x40, 0x6f, 0xb0, 0x58, 0x2c, 0x16, 0x13, 0x11, 0x90, 0xd0, 0x6f, 0xb0, 0x17, 0xf0
};
static const tImage Font_Let_9x13_0x32 = { image_data_Font_Let_9x13_0x32,
                                           9, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_Let_9x13_0x33[15] = {
  // ∙███████∙
  // █∙∙∙∙∙∙∙█
  // █∙█████∙█
  // █∙∙∙∙∙█∙█
  // █∙∙∙∙∙█∙█
  // █∙∙∙∙∙█∙█
  // █∙█████∙█
  // █∙∙∙∙∙█∙█
  // █∙∙∙∙∙█∙█
  // █∙∙∙∙∙█∙█
  // █∙█████∙█
  // █∙∙∙∙∙∙∙█
  // ∙███████∙
  0x7f, 0x40, 0x6f, 0xb0, 0x58, 0x2c, 0x16, 0xfb, 0x05, 0x82, 0xc1, 0x6f, 0xb0, 0x17, 0xf0
};
static const tImage Font_Let_9x13_0x33 = { image_data_Font_Let_9x13_0x33,
                                           9, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_Let_9x13_0x34[15] = {
  // ∙███████∙
  // █∙∙∙∙∙∙∙█
  // █∙∙∙∙█∙∙█
  // █∙∙∙██∙∙█
  // █∙∙█∙█∙∙█
  // █∙∙█∙█∙∙█
  // █∙█∙∙█∙∙█
  // █∙█∙∙█∙∙█
  // █∙█████∙█
  // █∙∙∙∙█∙∙█
  // █∙∙∙∙█∙∙█
  // █∙∙∙∙∙∙∙█
  // ∙███████∙
  0x7f, 0x40, 0x61, 0x31, 0x99, 0x4c, 0xa6, 0x93, 0x49, 0xbe, 0xc2, 0x61, 0x30, 0x17, 0xf0
};
static const tImage Font_Let_9x13_0x34 = { image_data_Font_Let_9x13_0x34,
                                           9, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_Let_9x13_0x35[15] = {
  // ∙███████∙
  // █∙∙∙∙∙∙∙█
  // █∙█████∙█
  // █∙█∙∙∙∙∙█
  // █∙█∙∙∙∙∙█
  // █∙█████∙█
  // █∙∙∙∙∙█∙█
  // █∙∙∙∙∙█∙█
  // █∙∙∙∙∙█∙█
  // █∙∙∙∙∙█∙█
  // █∙█████∙█
  // █∙∙∙∙∙∙∙█
  // ∙███████∙
  0x7f, 0x40, 0x6f, 0xb4, 0x1a, 0x0d, 0xf6, 0x0b, 0x05, 0x82, 0xc1, 0x6f, 0xb0, 0x17, 0xf0
};
static const tImage Font_Let_9x13_0x35 = { image_data_Font_Let_9x13_0x35,
                                           9, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_Let_9x13_0x36[15] = {
  // ∙███████∙
  // █∙∙∙∙∙∙∙█
  // █∙█████∙█
  // █∙█∙∙∙∙∙█
  // █∙█∙∙∙∙∙█
  // █∙█████∙█
  // █∙█∙∙∙█∙█
  // █∙█∙∙∙█∙█
  // █∙█∙∙∙█∙█
  // █∙█∙∙∙█∙█
  // █∙█████∙█
  // █∙∙∙∙∙∙∙█
  // ∙███████∙
  0x7f, 0x40, 0x6f, 0xb4, 0x1a, 0x0d, 0xf6, 0x8b, 0x45, 0xa2, 0xd1, 0x6f, 0xb0, 0x17, 0xf0
};
static const tImage Font_Let_9x13_0x36 = { image_data_Font_Let_9x13_0x36,
                                           9, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_Let_9x13_0x37[15] = {
  // ∙███████∙
  // █∙∙∙∙∙∙∙█
  // █∙█████∙█
  // █∙∙∙∙∙█∙█
  // █∙∙∙∙∙█∙█
  // █∙∙∙∙█∙∙█
  // █∙∙∙∙█∙∙█
  // █∙∙∙∙█∙∙█
  // █∙∙∙█∙∙∙█
  // █∙∙∙█∙∙∙█
  // █∙∙∙█∙∙∙█
  // █∙∙∙∙∙∙∙█
  // ∙███████∙
  0x7f, 0x40, 0x6f, 0xb0, 0x58, 0x2c, 0x26, 0x13, 0x09, 0x88, 0xc4, 0x62, 0x30, 0x17, 0xf0
};
static const tImage Font_Let_9x13_0x37 = { image_data_Font_Let_9x13_0x37,
                                           9, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_Let_9x13_0x38[15] = {
  // ∙███████∙
  // █∙∙∙∙∙∙∙█
  // █∙█████∙█
  // █∙█∙∙∙█∙█
  // █∙█∙∙∙█∙█
  // █∙█∙∙∙█∙█
  // █∙█████∙█
  // █∙█∙∙∙█∙█
  // █∙█∙∙∙█∙█
  // █∙█∙∙∙█∙█
  // █∙█████∙█
  // █∙∙∙∙∙∙∙█
  // ∙███████∙
  0x7f, 0x40, 0x6f, 0xb4, 0x5a, 0x2d, 0x16, 0xfb, 0x45, 0xa2, 0xd1, 0x6f, 0xb0, 0x17, 0xf0
};
static const tImage Font_Let_9x13_0x38 = { image_data_Font_Let_9x13_0x38,
                                           9, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_Let_9x13_0x39[15] = {
  // ∙███████∙
  // █∙∙∙∙∙∙∙█
  // █∙█████∙█
  // █∙█∙∙∙█∙█
  // █∙█∙∙∙█∙█
  // █∙█∙∙∙█∙█
  // █∙█∙∙∙█∙█
  // █∙█████∙█
  // █∙∙∙∙∙█∙█
  // █∙∙∙∙∙█∙█
  // █∙█████∙█
  // █∙∙∙∙∙∙∙█
  // ∙███████∙
  0x7f, 0x40, 0x6f, 0xb4, 0x5a, 0x2d, 0x16, 0x8b, 0x7d, 0x82, 0xc1, 0x6f, 0xb0, 0x17, 0xf0
};
static const tImage Font_Let_9x13_0x39 = { image_data_Font_Let_9x13_0x39,
                                           9, 13, 8};
#endif


static const tChar Font_Let_9x13_array[] = {

#if (0x0 == 0x0)
  // character: '0'
  {0x30, &Font_Let_9x13_0x30},
#else
// character: '0' == ''
  {0x30, &Font_Let_9x13_0x},
#endif

#if (0x0 == 0x0)
  // character: '1'
  {0x31, &Font_Let_9x13_0x31},
#else
// character: '1' == ''
  {0x31, &Font_Let_9x13_0x},
#endif

#if (0x0 == 0x0)
  // character: '2'
  {0x32, &Font_Let_9x13_0x32},
#else
// character: '2' == ''
  {0x32, &Font_Let_9x13_0x},
#endif

#if (0x0 == 0x0)
  // character: '3'
  {0x33, &Font_Let_9x13_0x33},
#else
// character: '3' == ''
  {0x33, &Font_Let_9x13_0x},
#endif

#if (0x0 == 0x0)
  // character: '4'
  {0x34, &Font_Let_9x13_0x34},
#else
// character: '4' == ''
  {0x34, &Font_Let_9x13_0x},
#endif

#if (0x0 == 0x0)
  // character: '5'
  {0x35, &Font_Let_9x13_0x35},
#else
// character: '5' == ''
  {0x35, &Font_Let_9x13_0x},
#endif

#if (0x0 == 0x0)
  // character: '6'
  {0x36, &Font_Let_9x13_0x36},
#else
// character: '6' == ''
  {0x36, &Font_Let_9x13_0x},
#endif

#if (0x0 == 0x0)
  // character: '7'
  {0x37, &Font_Let_9x13_0x37},
#else
// character: '7' == ''
  {0x37, &Font_Let_9x13_0x},
#endif

#if (0x0 == 0x0)
  // character: '8'
  {0x38, &Font_Let_9x13_0x38},
#else
// character: '8' == ''
  {0x38, &Font_Let_9x13_0x},
#endif

#if (0x0 == 0x0)
  // character: '9'
  {0x39, &Font_Let_9x13_0x39}
#else
// character: '9' == ''
  {0x39, &Font_Let_9x13_0x}
#endif

};


const tFont Font_Let_9x13 = { 10, Font_Let_9x13_array };

