#ifndef SSD1306_DEFINES_H_
#define SSD1306_DEFINES_H_

#include "stm32f1xx_hal.h"
#include <stdlib.h>
#include <string.h>
#include "stdbool.h"

//#define USE_DMA					    // uncomment if used I2C DMA mode
#define STM32_I2C_PORT		hi2c1 	// I2C port as defined in main generated by CubeMx
#define SSD1306_ADDRESS		0x3C	// I2C address display
#define SSD1306_128X32				// OR #define SSD1306_128X32

#endif /* SSD1306_DEFINES_H_ */
