
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* image
* filename: /Users/vitaliy/Fonts/In/Image_Set_8V.xml
* name: Image_Set_8V
*
* preset name: My_Settings
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 128
* split to rows: no
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: yes
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
*/
#include "image.h"



static const uint8_t image_data_Image_Set_8V[36] = {
        // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
        // ∙∙█████∙∙∙∙██████∙
        // ∙███████∙∙∙██████∙
        // ∙██∙∙∙██∙∙∙██∙∙██∙
        // ∙██∙∙∙██∙∙∙██∙∙██∙
        // ∙██∙∙∙██∙∙∙∙∙∙∙██∙
        // ∙███████∙∙∙∙∙∙∙██∙
        // ∙∙█████∙∙∙∙∙∙∙██∙∙
        // ∙███████∙∙∙∙∙██∙∙∙
        // ∙██∙∙∙██∙∙∙∙██∙∙∙∙
        // ∙██∙∙∙██∙∙∙██∙∙∙∙∙
        // ∙██∙∙∙██∙∙∙██∙∙∙∙∙
        // ∙██∙∙∙██∙∙∙██∙∙∙∙∙
        // ∙███████∙∙∙██████∙
        // ∙∙█████∙∙█∙██████∙
        // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
        0x00, 0x00, 0x0f, 0x87, 0xe7, 0xf1, 0xf9, 0x8c, 0x66, 0x63, 0x19, 0x98, 0xc0, 0x67, 0xf0, 0x18, 0xf8, 0x0c, 0x7f, 0x06, 0x18, 0xc3, 0x06, 0x31, 0x81, 0x8c, 0x60, 0x63, 0x18, 0x1f, 0xc7, 0xe3, 0xe5, 0xf8, 0x00, 0x00
};
const tImage Image_Set_8V = { image_data_Image_Set_8V, 18, 16,
                              8 };
