
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* image
* filename: /Users/vitaliy/Fonts/In/Image_Frame_20x18.xml
* name: Image_Frame_20x18
*
* preset name: My_Settings
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 128
* split to rows: no
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: yes
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
*/
#include "fonts.h"



static const uint8_t image_data_Image_Frame_22x20[55] = {
        // ∙████████████████████∙
        // █∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙█
        // █∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙█
        // █∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙█
        // █∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙█
        // █∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙█
        // █∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙█
        // █∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙█
        // █∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙█
        // █∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙█
        // █∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙█
        // █∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙█
        // █∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙█
        // █∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙█
        // █∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙█
        // █∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙█
        // █∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙█
        // █∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙█
        // █∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙█
        // ∙████████████████████∙
        0x7f, 0xff, 0xfa, 0x00, 0x00, 0x18, 0x00, 0x00, 0x60, 0x00, 0x01, 0x80, 0x00, 0x06, 0x00, 0x00, 0x18, 0x00, 0x00, 0x60, 0x00, 0x01, 0x80, 0x00, 0x06, 0x00, 0x00, 0x18, 0x00, 0x00, 0x60, 0x00, 0x01, 0x80, 0x00, 0x06, 0x00, 0x00, 0x18, 0x00, 0x00, 0x60, 0x00, 0x01, 0x80, 0x00, 0x06, 0x00, 0x00, 0x18, 0x00, 0x00, 0x5f, 0xff, 0xfe
};
const tImage Image_Frame_22x20 = { image_data_Image_Frame_22x20, 22, 20,
                                   8 };
