
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* image
* filename: /Users/vitaliy/Fonts/In/Image_Set_Low_Volt.xml
* name: Image_Set_Low_Volt
*
* preset name: My_Settings
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 128
* split to rows: no
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: yes
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
*/
#include "fonts.h"



static const uint8_t image_data_Image_Set_Low_Volt[79] = {
        // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
        // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
        // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
        // ∙∙∙██████████████████∙∙∙∙
        // ∙∙█∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙█∙∙∙
        // ∙∙█∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙█∙∙∙
        // ∙∙█∙█∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙██∙∙
        // ∙∙█∙██∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙██∙∙
        // ∙∙█∙█∙█∙∙∙∙∙∙∙∙∙∙∙∙∙∙██∙∙
        // ∙∙█∙█∙∙█∙∙∙∙∙∙∙∙∙∙∙∙∙██∙∙
        // ∙∙█∙█████∙∙∙∙∙∙∙∙∙∙∙∙█∙∙∙
        // ∙∙█∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙█∙∙∙
        // ∙∙∙██████████████████∙∙∙∙
        // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
        // ∙∙∙∙∙∙█∙∙∙█∙∙∙∙∙∙∙∙∙∙∙∙∙∙
        // ∙∙∙∙∙∙██∙██∙∙∙∙∙∙∙∙∙∙∙∙∙∙
        // ∙∙∙∙∙∙█∙█∙█∙█∙███∙∙∙∙∙∙∙∙
        // ∙∙∙∙∙∙█∙∙∙█∙∙∙█∙∙█∙∙∙∙∙∙∙
        // ∙∙∙∙∙∙█∙∙∙█∙█∙█∙∙█∙∙∙∙∙∙∙
        // ∙∙∙∙∙∙█∙∙∙█∙█∙█∙∙█∙∙∙∙∙∙∙
        // ∙∙∙∙∙∙█∙∙∙█∙█∙█∙∙█∙∙∙∙∙∙∙
        // ∙∙∙∙∙∙█∙∙∙█∙█∙█∙∙█∙∙∙∙∙∙∙
        // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
        // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
        // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x03, 0xff, 0xff, 0x02, 0x00, 0x00, 0x41, 0x00, 0x00, 0x20, 0xa0, 0x00, 0x18, 0x58, 0x00, 0x0c, 0x2a, 0x00, 0x06, 0x14, 0x80, 0x03, 0x0b, 0xe0, 0x01, 0x04, 0x00, 0x00, 0x81, 0xff, 0xff, 0x80, 0x00, 0x00, 0x00, 0x08, 0x80, 0x00, 0x06, 0xc0, 0x00, 0x02, 0xab, 0x80, 0x01, 0x11, 0x20, 0x00, 0x8a, 0x90, 0x00, 0x45, 0x48, 0x00, 0x22, 0xa4, 0x00, 0x11, 0x52, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x7f
};
const tImage Image_Set_Low_Volt = { image_data_Image_Set_Low_Volt, 25, 25,
    8 };
