
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* image
* filename: /Users/vitaliy/Fonts/In/Image_Current_In.xml
* name: Image_Current_In
*
* preset name: My_Settings
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 128
* split to rows: no
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: yes
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
*/
#include "fonts.h"



static const uint8_t image_data_Image_Current_In[22] = {
    // ∙███████████████∙
    // █∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙█
    // █∙∙█∙∙∙∙∙∙∙∙█∙∙∙█
    // █∙∙█∙∙∙∙∙∙∙█∙█∙∙█
    // █∙∙█∙██∙∙∙∙█∙█∙∙█
    // █∙∙█∙█∙█∙█∙███∙∙█
    // █∙∙█∙█∙█∙∙∙█∙█∙∙█
    // █∙∙█∙█∙█∙∙∙█∙█∙∙█
    // █∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙█
    // ∙███████████████∙
    0x7f, 0xff, 0x40, 0x00, 0x64, 0x02, 0x32, 0x02, 0x99, 0x61, 0x4c, 0xaa, 0xe6, 0x54, 0x53, 0x2a, 0x29, 0x80, 0x00, 0xbf, 0xff, 0xbf
};
const tImage Image_Current_In = { image_data_Image_Current_In, 17, 10,
    8 };
