
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* image
* filename: /Users/vitaliy/Fonts/In/Image_Set_V_Out.xml
* name: Image_Set_V_Out
*
* preset name: My_Settings
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 128
* split to rows: no
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: yes
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
*/
#include "fonts.h"



static const uint8_t image_data_Image_Set_V_Out[79] = {
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙███∙∙∙∙█████∙∙█∙∙∙∙█∙∙
    // ∙∙█∙∙∙█∙∙∙█∙∙∙█∙∙█∙∙∙∙█∙∙
    // ∙∙█∙∙∙█∙∙∙∙∙∙∙█∙∙█∙∙∙∙█∙∙
    // ∙∙█∙∙∙█∙∙∙∙∙∙∙█∙∙██∙∙██∙∙
    // ∙∙∙███∙∙∙∙∙∙∙∙█∙∙∙█∙∙█∙∙∙
    // ∙∙█∙∙∙█∙∙∙∙∙∙█∙∙∙∙█∙∙█∙∙∙
    // ∙∙█∙∙∙█∙∙∙∙∙█∙∙∙∙∙████∙∙∙
    // ∙∙█∙∙∙█∙∙∙∙█∙∙∙∙∙∙∙██∙∙∙∙
    // ∙∙█∙∙∙█∙∙∙█∙∙∙∙∙∙∙∙██∙∙∙∙
    // ∙∙∙███∙∙█∙█████∙∙∙∙██∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙█████████████████████∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙██∙∙█████∙∙█∙∙∙∙█∙∙∙∙
    // ∙∙∙∙∙█∙∙█∙∙∙█∙∙█∙∙∙∙█∙∙∙∙
    // ∙∙∙∙∙█∙∙∙∙∙∙█∙∙█∙∙∙∙█∙∙∙∙
    // ∙∙∙∙∙█∙∙∙∙∙∙█∙∙██∙∙██∙∙∙∙
    // ∙∙∙∙∙█∙∙∙∙∙∙█∙∙∙█∙∙█∙∙∙∙∙
    // ∙∙∙∙∙█∙∙∙∙∙█∙∙∙∙█∙∙█∙∙∙∙∙
    // ∙∙∙∙∙█∙∙∙∙█∙∙∙∙∙████∙∙∙∙∙
    // ∙∙∙∙∙█∙∙∙█∙∙∙∙∙∙∙██∙∙∙∙∙∙
    // ∙∙∙∙∙█∙∙█∙∙∙∙∙∙∙∙██∙∙∙∙∙∙
    // ∙∙∙∙███∙█████∙∙∙∙██∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x0e, 0x1f, 0x21, 0x08, 0x88, 0x90, 0x84, 0x40, 0x48, 0x42, 0x20, 0x26, 0x60, 0xe0, 0x11, 0x20, 0x88, 0x10, 0x90, 0x44, 0x10, 0x78, 0x22, 0x10, 0x18, 0x11, 0x10, 0x0c, 0x07, 0x2f, 0x86, 0x00, 0x00, 0x00, 0x03, 0xff, 0xff, 0xe0, 0x00, 0x00, 0x00, 0x33, 0xe4, 0x20, 0x09, 0x12, 0x10, 0x04, 0x09, 0x08, 0x02, 0x04, 0xcc, 0x01, 0x02, 0x24, 0x00, 0x82, 0x12, 0x00, 0x42, 0x0f, 0x00, 0x22, 0x03, 0x00, 0x12, 0x01, 0x80, 0x1d, 0xf0, 0xc0, 0x00, 0x00, 0x00, 0x7f
};
const tImage Image_Set_V_Out = { image_data_Image_Set_V_Out, 25, 25,
    8 };
