
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* image
* filename: /Users/vitaliy/Fonts/In/Image_Battery_Type_Ico.xml
* name: Image_Battery_Type_Ico
*
* preset name: My_Settings
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 128
* split to rows: no
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: yes
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
*/
#include "fonts.h"



static const uint8_t image_data_Image_Battery_Type_Ico[22] = {
    // ∙███████████████∙
    // █∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙█
    // █∙∙██∙∙∙█∙∙███∙∙█
    // █∙∙█∙█∙█∙█∙∙█∙∙∙█
    // █∙∙███∙███∙∙█∙∙∙█
    // █∙∙█∙█∙█∙█∙∙█∙∙∙█
    // █∙∙█∙█∙█∙█∙∙█∙∙∙█
    // █∙∙██∙∙█∙█∙∙█∙∙∙█
    // █∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙█
    // ∙███████████████∙
    0x7f, 0xff, 0x40, 0x00, 0x66, 0x27, 0x32, 0xa9, 0x19, 0xdc, 0x8c, 0xaa, 0x46, 0x55, 0x23, 0x32, 0x91, 0x80, 0x00, 0xbf, 0xff, 0xbf
};
const tImage Image_Battery_Type_Ico = { image_data_Image_Battery_Type_Ico, 17, 10,
    8 };
